[package]
name = "ipv4or6"
version = "0.1.0"
authors = ["William of Ockham <Occam_Engineering@comcast.com>"]

[dependencies]
netbricks = { path = "../../framework"}
colored = ">=1.6"

[features]
default = []
print = []
