[package]
name = "chain"
version = "0.1.0"
authors = ["Aurojit Panda <apanda@cs.berkeley.edu>", "William of Ockham <williamofockham@gmail.com>"]

[dependencies]
getopts = "*"
netbricks = { path = "../../framework" }

[features]
default = []
print = []
