secondary = false
primary_core = 0
cores = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
strict = false
pool_size = 4096
cache_size = 32
duration = 1800
[[ports]]
  name = "0000:02:00.0"
  rx_queues = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  tx_queues = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  rxd = 128
  txd = 128
  loopback = false
  tso = false
  csum = false