[package]
name = "acl-fw"
version = "0.1.0"
authors = ["Aurojit Panda <apanda@cs.berkeley.edu>", "William of Ockham <williamofockham@gmail.com>"]

[dependencies]
fnv = "*"
lazy_static = "*"
netbricks = { path = "../../framework"}

[features]
default = []
print = []
