[package]
name = "op-errors"
version = "0.1.0"
authors = ["William of Ockham <Occam_Engineering@comcast.com>"]

[dependencies]
netbricks = { path = "../../framework"}
failure = "0.1.5"
log = "*"
simplelog = "*"

[features]
default = []
print = []
